# Generated by Django 5.1.6 on 2026-02-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('MA', 'Morocco'), ('DZ', 'Algeria')], default='DZ', max_length=2),
        ),
    ]
