# Generated by Django 5.1.6 on 2025-08-18 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpage',
            old_name='custom_pixels',
            new_name='pixels',
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landingpages', to='products.product'),
        ),
    ]
