# Generated by Django 5.1.6 on 2025-08-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0002_rename_custom_pixels_landingpage_pixels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='thank_you_html',
            field=models.TextField(blank=True, default='<div class="container">\n        <div class="success-icon">\n        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 52 52">\n            <path d="M26 0C11.664 0 0 11.664 0 26s11.664 26 26 26 26-11.664 26-26S40.336 0 26 0zm0 48C13.215 48 4 38.785 4 26S13.215 4 26 4s22 9.215 22 22-9.215 22-22 22zm-3.172-14.828l-7.778-7.778-2.828 2.828 10.606 10.606L39.778 17.778l-2.828-2.828-14.122 14.122z"></path>\n        </svg>\n        </div>\n        <h1>تم الطلب بنجاح!</h1>\n        <p>شكراً لشرائك من متجرنا. تم تأكيد طلبك وهو الآن في طريقه إليك!</p>\n    </div>', null=True),
        ),
    ]
