# Generated by Django 5.1.6 on 2025-08-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0003_landingpage_thank_you_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='thank_you_html',
            field=models.TextField(blank=True, default='<div class="container" dir="rtl">\n        <div class="success-icon" style="text-align:center"><strong><span style="color:#2ecc71"><span style="font-family:Verdana,Geneva,sans-serif"><span dir="rtl"><span style="font-size:26px">تم الطلب بنجاح!</span></span></span></span></strong></div>\n\n        <p style="text-align:center"><span style="color:#ffffff"><span style="font-family:Verdana,Geneva,sans-serif"><span dir="rtl"><span style="font-size:26px"><span style="background-color:#27ae60">شكراً لشرائك من متجرنا. تم تأكيد طلبك وهو الآن في طريقه إليك!</span></span></span></span></span></p>\n        </div>', null=True),
        ),
    ]
