# Generated by Django 5.1.6 on 2026-02-27 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0004_alter_landingpage_thank_you_html'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
