# Generated by Django 5.1.6 on 2025-08-18 16:16

import django.db.models.deletion
import stores.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sheet_webhook', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('FB_PAGE', models.CharField(blank=True, max_length=255, null=True)),
                ('INSTA_PAGE', models.CharField(blank=True, max_length=255, null=True)),
                ('PHONE_NUMBER', models.CharField(blank=True, max_length=255, null=True)),
                ('EMAIL', models.CharField(blank=True, max_length=255, null=True)),
                ('WHATSAPP', models.CharField(blank=True, max_length=255, null=True)),
                ('THEME_COLOR', models.CharField(blank=True, max_length=255, null=True)),
                ('LOGO', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block_settings', models.JSONField(default=stores.models.Store.default_block_settings)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pixels', to='stores.store')),
            ],
        ),
    ]
