# Generated by Django 5.1.6 on 2025-08-12 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='EMAIL',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='FB_PAGE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='FB_PIXEL',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='INSTA_PAGE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='LOGO',
            field=models.ImageField(null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='store',
            name='PHONE_NUMBER',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='THEME_COLOR',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='WHATSAPP',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='site',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('أدرار', 'أدرار'), (' الشلف', ' الشلف'), ('الأغواط', 'الأغواط'), ('أم البواقي', 'أم البواقي'), ('باتنة', 'باتنة'), (' بجاية', ' بجاية'), ('بسكرة', 'بسكرة'), ('بشار', 'بشار'), ('البليدة', 'البليدة'), ('البويرة', 'البويرة'), ('تمنراست', 'تمنراست'), ('تبسة', 'تبسة'), ('تلمسان', 'تلمسان'), ('تيارت', 'تيارت'), ('تيزي وزو', 'تيزي وزو'), ('الجزائر', 'الجزائر'), ('الجلفة', 'الجلفة'), ('جيجل', 'جيجل'), ('سطيف', 'سطيف'), ('سعيدة', 'سعيدة'), ('سكيكدة', 'سكيكدة'), ('سيدي بلعباس', 'سيدي بلعباس'), ('عنابة', 'عنابة'), ('قالمة', 'قالمة'), ('قسنطينة', 'قسنطينة'), ('المدية', 'المدية'), ('مستغانم', 'مستغانم'), ('المسيلة', 'المسيلة'), ('معسكر', 'معسكر'), ('ورقلة', 'ورقلة'), ('وهران', 'وهران'), ('البيض', 'البيض'), ('إليزي', 'إليزي'), ('برج بوعريريج', 'برج بوعريريج'), ('بومرداس', 'بومرداس'), ('الطارف', 'الطارف'), ('تندوف', 'تندوف'), ('تيسمسيلت', 'تيسمسيلت'), ('الوادي', 'الوادي'), ('خنشلة', 'خنشلة'), ('سوق أهراس', 'سوق أهراس'), ('تيبازة', 'تيبازة'), ('ميلة', 'ميلة'), ('عين الدفلة', 'عين الدفلة'), ('النعامة', 'النعامة'), ('عين تيموشنت', 'عين تيموشنت'), ('غرداية', 'غرداية'), ('غليزان', 'غليزان'), ('تيميمون', 'تيميمون'), ('برج باجي مختار', 'برج باجي مختار'), ('أولاد جلال', 'أولاد جلال'), ('بني عباس', 'بني عباس'), ('عين صالح', 'عين صالح'), ('عين قزام', 'عين قزام'), ('تقرت', 'تقرت'), ('جانت', 'جانت'), ('المغير', 'المغير'), ('المنيعة', 'المنيعة')], max_length=255, unique=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='stores.store')),
            ],
        ),
    ]
