# Generated by Django 5.1.6 on 2025-08-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='FAKE_PIXEL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
