# Generated by Django 5.1.6 on 2026-02-27 02:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_fake_pixel'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='stores.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'name'), name='unique_store_city')],
                'unique_together': {('store', 'name')},
            },
        ),
    ]
