# Generated by Django 5.1.6 on 2025-08-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_email_store_fb_page_store_fb_pixel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='sheet_webhook',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
