# Generated by Django 5.1.6 on 2025-03-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('home_delivery', 'Delivery to home'), ('stop_desk', 'Stop desk')], default='home_delivery', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
