# Generated by Django 5.1.6 on 2025-03-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_method_order_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='http_referer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
