# Generated by Django 5.1.6 on 2026-02-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_landing_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('in_confirmation', 'In Confirmation'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('archived', 'Archived'), ('blocked', 'Blocked')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('in_confirmation', 'In Confirmation'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('archived', 'Archived'), ('blocked', 'Blocked')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='previous_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('in_confirmation', 'In Confirmation'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('archived', 'Archived'), ('blocked', 'Blocked')], max_length=20),
        ),
    ]
