# Generated by Django 5.1.6 on 2026-03-06 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_alter_statushistory_new_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statushistory',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AddField(
            model_name='statushistory',
            name='action',
            field=models.CharField(choices=[('status_change', 'Status change'), ('order_update', 'Order updated'), ('item_update', 'Item updated'), ('item_add', 'Item added'), ('item_delete', 'Item deleted')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statushistory',
            name='field_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='new_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='previous_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.CharField(blank=True, choices=[('in_progress', 'In Progress'), ('in_confirmation', 'In Confirmation'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('archived', 'Archived'), ('blocked', 'Blocked')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('in_progress', 'In Progress'), ('in_confirmation', 'In Confirmation'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('archived', 'Archived'), ('blocked', 'Blocked')], max_length=20, null=True),
        ),
    ]
