# Generated by Django 5.1.6 on 2025-03-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SKU',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
