# Generated by Django 5.1.6 on 2026-03-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='offer_label',
            field=models.CharField(blank=True, help_text='Display label shown to the customer, e.g. "Buy 2 for $15" (offers only).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(choices=[('option', 'Option'), ('offer', 'Offer')], default='option', max_length=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='option_values',
            field=models.ManyToManyField(blank=True, related_name='variants', to='products.productoptionvalue'),
        ),
    ]
